#!/usr/bin/env python3
"""Generate _includes/exploded.html — the isometric exploded view on the
landing page. Geometry is computed here once; the include only switches the
label strings by language. Re-run after editing LAYERS:

    python3 tools/gen_exploded.py
"""
from pathlib import Path

CX, A, B, T = 172, 142, 71, 12        # centre x, half-width, half-height, plate thickness
Y0, STEP, TIGHT = 474, 88, 18          # bottom plate centre, exploded spacing, collapsed spacing
LX = CX + A + 50                       # label column x

# bottom -> top. (pattern, en title, en sub, ja title, ja sub, en href, ja href)
LAYERS = [
    ("grid",  "Hardware",  "GPUs on a network you control",
              "ハードウェア", "自社で管理するGPUとLAN",
              "/writing/quantisation-for-your-hardware/", "/ja/writing"),
    ("diag",  "Inference", "llama.cpp · Ollama · GGUF quants",
              "推論", "llama.cpp・Ollama・GGUF量子化",
              "/projects/#llama-launcher", "/ja/projects/#llama-launcher"),
    ("dots",  "Tools",     "MCP servers · WASI sandboxes",
              "ツール", "MCPサーバ・WASIサンドボックス",
              "/experience", "/ja/experience"),
    ("cross", "Agents",    "tool-calling · RAG · multi-agent",
              "エージェント", "ツール呼び出し・RAG・マルチエージェント",
              "/projects/aios/", "/ja/projects/aios/"),
    ("lines", "Products",  "AIOS · Rootward · Work Hub",
              "プロダクト", "AIOS・Rootward・Work Hub",
              "/projects/", "/ja/projects/"),
]

def rhomb(yc):
    return f"{CX-A},{yc} {CX},{yc-B} {CX+A},{yc} {CX},{yc+B}"

def side_l(yc):
    return f"{CX-A},{yc} {CX},{yc+B} {CX},{yc+B+T} {CX-A},{yc+T}"

def side_r(yc):
    return f"{CX},{yc+B} {CX+A},{yc} {CX+A},{yc+T} {CX},{yc+B+T}"

PATTERNS = """
    <pattern id="xv-grid" width="12" height="12" patternUnits="userSpaceOnUse"><path class="hatch" d="M0 0H12M0 0V12"/></pattern>
    <pattern id="xv-diag" width="9" height="9" patternUnits="userSpaceOnUse" patternTransform="rotate(-30)"><path class="hatch" d="M0 0V9"/></pattern>
    <pattern id="xv-dots" width="10" height="10" patternUnits="userSpaceOnUse"><circle class="glyph-fill" cx="5" cy="5" r="1.1"/></pattern>
    <pattern id="xv-cross" width="11" height="11" patternUnits="userSpaceOnUse" patternTransform="rotate(30)"><path class="hatch" d="M0 0V11M0 0H11"/></pattern>
    <pattern id="xv-lines" width="8" height="8" patternUnits="userSpaceOnUse" patternTransform="rotate(26.6)"><path class="hatch" d="M0 0H8"/></pattern>"""

out = []
out.append("""{%- comment -%}
  GENERATED by tools/gen_exploded.py — edit the script, not this file.
  Isometric exploded view of the stack. Plates start collapsed (html.js
  only) and separate when scrolled into view; labels link to evidence.
{%- endcomment -%}
{%- assign ja = false -%}{%- if include.lang == "ja" -%}{%- assign ja = true -%}{%- endif -%}
<figure class="exploded draw" aria-labelledby="xv-cap">""")
H = Y0 + B + T + 14
out.append(f'  <svg viewBox="0 0 640 {H}" role="group" aria-labelledby="xv-title">')
out.append('    <title id="xv-title">{% if ja %}分解図：ハードウェアからプロダクトまで、5層の技術スタック{% else %}Exploded view: a five-layer stack from hardware to products{% endif %}</title>')
out.append(f"    <defs>{PATTERNS}")
for i in range(len(LAYERS)):
    yc = Y0 - i * STEP
    out.append(f'      <clipPath id="xv-c{i}"><polygon points="{rhomb(yc)}"/></clipPath>')
out.append("    </defs>")
top_y = Y0 - (len(LAYERS) - 1) * STEP - B - 22
out.append(f'    <path class="xv-axis" d="M{CX} {top_y} V{H - 4}"/>')

for i, (pat, et, es, jt, js, eh, jh) in enumerate(LAYERS):
    yc = Y0 - i * STEP
    collapse = i * (STEP - TIGHT)
    n = f"{i+1:02d}"
    out.append(f'    <g class="xv-group">')
    out.append(f'      <g class="xv-plate" style="--collapse:{collapse}px">')
    out.append(f'        <polygon class="side-l" points="{side_l(yc)}"/>')
    out.append(f'        <polygon class="side-r" points="{side_r(yc)}"/>')
    out.append(f'        <polygon class="top" points="{rhomb(yc)}"/>')
    out.append(f'        <rect x="{CX-A}" y="{yc-B}" width="{2*A}" height="{2*B}" fill="url(#xv-{pat})" clip-path="url(#xv-c{i})" style="pointer-events:none"/>')
    out.append(f'      </g>')
    out.append(f'      <circle class="xv-dot" cx="{CX+A}" cy="{yc}" r="2.6"/>')
    out.append(f'      <path class="xv-lead" d="M{CX+A+4} {yc} H{LX-8}"/>')
    out.append(f'      <a class="xv-label" href="{{% if ja %}}{{{{ "{jh}" | relative_url }}}}{{% else %}}{{{{ "{eh}" | relative_url }}}}{{% endif %}}">')
    out.append(f'        <text class="n" x="{LX}" y="{yc-20}">{n}</text>')
    out.append(f'        <text class="t" x="{LX}" y="{yc+6}">{{% if ja %}}{jt}{{% else %}}{et}{{% endif %}}</text>')
    out.append(f'        <text class="s" x="{LX}" y="{yc+27}">{{% if ja %}}{js}{{% else %}}{es}{{% endif %}}</text>')
    out.append(f'      </a>')
    out.append(f'    </g>')
out.append("  </svg>")
out.append('  <figcaption id="xv-cap"><span class="t-label">{% if ja %}図1 — 分解図：開発の技術スタック{% else %}Fig. 1 — Exploded view: the stack I build on{% endif %}</span><span class="t-label">{% if ja %}尺度：非比例{% else %}Scale: NTS{% endif %}</span></figcaption>')
out.append("</figure>")

Path(__file__).resolve().parent.parent.joinpath("_includes/exploded.html").write_text("\n".join(out) + "\n")
print("wrote _includes/exploded.html")
